version: '2'
networks: 
  managment-network:
    external: true
services:
  postgresql:
    image: 'bitnami/postgresql:11'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_redmine
      - POSTGRESQL_DATABASE=bitnami_redmine
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    networks: 
      - managment-network      
  redmine:
    image: 'bitnami/redmine:4'
    ports:
      - '4198:3000'
    environment:
      - REDMINE_DB_POSTGRES=postgresql
      - REDMINE_DB_USERNAME=bn_redmine
      - REDMINE_DB_NAME=bitnami_redmine
    volumes:
      - './redmine_data:/bitnami'
      - './redmineFiles:/usr/src/redmine/files'
    networks: 
      - managment-network
    depends_on:
      - postgresql
volumes:
  postgresql_data:
    driver: local
  redmine_data: